#!/usr/bin/env python3
"""
A FIRE DRILL THAT CANNOT REPORT A FIRE IS NOT A DRILL.

🔴🔴 `[2026-09-15, run #7 — Sam: "ok so ive done this mutliple times but
your ssaying im not doing it"]` — **and he was right. He fired it seven
times. Every run went GREEN. Nothing was ever produced.**

```
self-repair [workflow_dispatch] #7
  triage   SUCCESS    5s
  fix      SUCCESS   45s
  →  no self-repair/drill branch
  →  no self-repair-drill.md
  →  no pull request
```

⛔ `claude-code-action@v1` **EXITS 0 WHETHER OR NOT THE AGENT DID THE
WORK.** So the one step whose entire purpose was to answer *"does this
path work?"* answered **yes** seven times while the path did not work.

🔴 **THAT IS THE ONE RULE THAT MATTERS MOST, BROKEN BY THE THING BUILT TO
UPHOLD IT:** *a green tick that proves nothing is worse than a red one,
because it gets trusted.* And I trusted it — I spent three messages
telling Sam he had not ticked a checkbox he had ticked, because my own
instrument reported nothing wrong. **The absence of evidence was being
generated by the instrument.**

⛔ **AND I COULD NOT SEE IT FROM HERE.** `api.github.com` is blocked to
this container, so "never fired" and "fired and did nothing" look
identical from the repo side — **the drill's output was the only thing
that could have told either of us apart, and it was lying.**

══════════════════════════════════════════════════════════════════════
✅ THE FIX: THE DRILL ASSERTS ITS OWN ARTIFACT.

Exactly one outcome is correct — a branch `self-repair/drill`, or a PR
from it. Anything else fails the job loudly, with the likely cause named.

⛔ AND THE REAL REPAIR PATH IS DELIBERATELY *NOT* ASSERTED THE SAME WAY.
It has a legitimate empty outcome: `CLAUDE.md` tells the agent that an
MLB finding gets a comment and NO code change. Failing on "no branch"
there would punish the agent for obeying the freeze — a guard firing on
correct behaviour, which is the other failure.

⚠️ THIS FILE EXECUTES THE REAL SHELL, pulled out of the workflow, against
a stub `git` and a stub `gh`. It does not read the YAML and agree with
itself (rule 260).
"""
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile

from tcheck import ck, note

ROOT = os.path.dirname(os.path.abspath(__file__))
WF = os.path.join(ROOT, ".github/workflows/self-repair.yml")
YML = open(WF, encoding="utf-8").read()

_m = re.search(r"- name: Did the drill actually do anything\?\n(.*)\Z",
               YML, re.S)
STEP = _m.group(1) if _m else ""
ck("🔴 the drill's proof step is present at all", bool(STEP) and len(STEP) > 300,
   "⛔ without it the drill reports SUCCESS having produced nothing — "
   "which it did seven times. Got %d chars" % len(STEP))

print("\n═══ 1. ⛔ IT RUNS EVEN WHEN THE AGENT STEP BLEW UP ═══")
ck("🔴 guarded by always(), not by the agent having succeeded",
   "if: always() && needs.triage.outputs.drill == 'yes'" in STEP,
   "⛔ a proof step that only runs on success cannot report the failure "
   "it exists to catch — it would be skipped in exactly the case that "
   "matters, and a skipped step is a silent one")
ck("⚠️ ...and only on a DRILL",
   "needs.triage.outputs.drill == 'yes'" in STEP,
   "⛔ the real repair path has a LEGITIMATE empty outcome: CLAUDE.md "
   "tells the agent an MLB finding gets a comment and no code change. "
   "Asserting a branch there would fail the agent for obeying the freeze")
ck("⛔ the real repair step is NOT given the same assertion",
   YML.count("THE DRILL PRODUCED NOTHING") == 1
   and "drill != 'yes'" in YML,
   "🔴 a guard that fires on correct behaviour is the other failure, not "
   "a safe one. The two paths have different correct outcomes and must "
   "not share one bar")

print("\n═══ 1b. 🔴🔴 THE AGENT IS ALLOWED TO ACT AT ALL ═══")
# 🔴🔴 RUN #8's LOG, AND IT KILLED MY LEADING SUSPICION:
#
#     "permission_denials_count": 3
#     "num_turns": 6   "duration_ms": 10701   "is_error": false
#     Verified human actor: smh0602   model: claude-sonnet-5
#     total_cost_usd: 0.105246
#
# ⛔ AUTH WAS NEVER BROKEN. OIDC exchanged, app token obtained, git
#    configured, Claude Code installed, real money spent. **I blamed the
#    OAuth secret three times and was wrong three times.** The agent
#    asked to do three things, was DENIED all three, and reported
#    `success` because nothing errored.
# ⚠️ WITHOUT AN ALLOWLIST IT CAN READ AND THINK AND NOTHING ELSE — no
#    file, no branch, no push, no PR. ➡️ **And that was equally true of
#    the REAL repair step**, so Tier 3 has never been capable of working
#    since the day it shipped.
# ⚠️ SPLIT ON THE `uses:` LINE, NOT THE BARE NAME. The action is also
#    named in a COMMENT above the job, and my first version split on the
#    bare string — three "steps", one of them prose. **A check over the
#    wrong set is the vacuous shape**, which is why the count is
#    asserted before anything is read off it.
_steps = YML.split("uses: anthropics/claude-code-action@v1")[1:]
ck("⚠️ both agent steps are findable",
   len(_steps) == 2,
   "⛔ a check over the wrong set proves nothing. Found %d" % len(_steps))
_missing = [i for i, b in enumerate(_steps) if "--allowedTools" not in b]
ck("🔴🔴 EVERY agent step grants tools — drill AND real repair",
   not _missing,
   "⛔ an agent with no allowlist can read and think and nothing else. "
   "It cannot write, branch, push or open a PR — it burns Sam's "
   "subscription and reports success. Steps missing it: %s" % _missing)
for _need in ("Write", "Edit", "Bash"):
    ck("⛔ ...including `%s`, without which there is no PR" % _need,
       all(_need in b.split("--allowedTools")[1][:200]
           for b in _steps if "--allowedTools" in b),
       "🔴 the drill must create a file, commit it and push a branch. "
       "Missing any one of Read/Write/Edit/Bash makes the whole path "
       "silently impossible")

print("\n═══ 1c. ⚠️ DIAGNOSIS WHERE IT IS SAFE, SILENCE WHERE IT IS NOT ═══")
# ⛔ The log said the detail was hidden "for security" and named the
#    switch. Turning it on is the only reason the NEXT failure will say
#    WHICH tool was denied rather than just counting them.
# ⚠️ But the repair prompt carries live findings from health.json into
#    a PUBLIC log, and the drill's prompt is fixed and harmless. So the
#    switch goes on exactly one of them.
ck("🔴 the DRILL prints full agent output",
   "show_full_output: true" in _steps[0],
   "⛔ run #8 counted three denials and named none. Without this the "
   "next failure is equally uninformative and we are back to guessing")
ck("⛔ ...and the REAL repair step does NOT",
   "show_full_output" not in _steps[1],
   "🔴 the repair prompt interpolates live findings into a PUBLIC "
   "run log. A diagnostic switch that is safe on a fixed harmless "
   "prompt is not safe on a variable one — and `gizmos-picks` is a "
   "public repo")

print("\n═══ 2. 🔴🔴 THE SHELL, ACTUALLY EXECUTED ═══")
_run = re.search(r"(?ms)^        run: \|\n(.*?)(?=\n      - name:|\Z)", STEP)
ck("🔴 the proof shell is extractable to be driven",
   bool(_run),
   "⛔ if this stops matching, every check below proves only that some "
   "strings are present in a YAML file — rule 260")

if _run:
    body = re.sub(r"(?m)^          ", "", _run.group(1))
    tmp = tempfile.mkdtemp()

    def drive(branches, prs):
        """Run the real shell with a stub git and gh. Returns (rc, out)."""
        binp = os.path.join(tmp, "bin")
        os.makedirs(binp, exist_ok=True)
        for name, payload in (("git", branches), ("gh", prs)):
            p = os.path.join(binp, name)
            # ⚠️ AN EMPTY ANSWER MUST BE GENUINELY EMPTY. A heredoc
            #    emits a blank line, which `wc -l` counts as ONE — and
            #    that is exactly the bug this fixture found in the real
            #    step. The stub has to be able to say NOTHING.
            open(p, "w").write("#!/bin/sh\nexit 0\n" if payload == ""
                               else "#!/bin/sh\nprintf '%%s\\n' '%s'\n"
                                    % payload)
            os.chmod(p, os.stat(p).st_mode | stat.S_IEXEC)
        env = dict(os.environ, PATH=binp + os.pathsep + os.environ["PATH"])
        r = subprocess.run(["bash", "-c", body], cwd=tmp, env=env,
                           capture_output=True, text=True, timeout=60)
        return r.returncode, r.stdout + r.stderr

    # ⛔ THE BITE, AND IT IS THE REAL RUN #7: agent exits 0, nothing made.
    rc, out = drive("", "0")
    ck("🔴🔴 NOTHING PRODUCED → the job FAILS",
       rc != 0,
       "⛔ THIS IS RUN #7. `fix` reported SUCCESS in 45 seconds with no "
       "branch, no file and no PR, seven times running. rc=%d" % rc)
    ck("✅ ...and it names the likely cause instead of just going red",
       "exits 0 even when the agent could not act" in out,
       "🔴 'it failed' sends the reader nowhere. The one thing worth "
       "saying is that the action's own exit code cannot be trusted, "
       "because that is what made this invisible. Got: %s" % out[-160:])
    ck("⛔ ...and the error reaches the run page as an annotation",
       "::error::" in out,
       "a failure with no annotation is a failure somebody has to go "
       "hunting for")

    # ✅ AND THE OTHER DIRECTION — it must go quiet when the drill worked.
    rc2, out2 = drive("abc123\trefs/heads/self-repair/drill", "0")
    ck("✅ a branch alone is enough to PASS",
       rc2 == 0 and "the Tier 3 path works" in out2,
       "⛔ a guard that fires on correct behaviour is the other failure. "
       "rc=%d out=%s" % (rc2, out2[-120:]))
    rc3, out3 = drive("", "1")
    ck("✅ ...and so is a PR alone",
       rc3 == 0,
       "🔴 the agent may open the PR and GitHub may have already tidied "
       "the branch. EITHER artifact proves the path ran. rc=%d" % rc3)

    # ⚠️ AND THE COUNT MUST COME FROM THE ANSWER, NOT FROM A CRASH.
    # ⛔ A COMMAND THAT PRINTS AN EMPTY LINE IS NOT A COMMAND THAT FOUND
    #    SOMETHING. `wc -l` counts the newline and reports ONE — a
    #    phantom branch, and the drill passes on nothing for the eighth
    #    time. `grep -c .` counts non-empty lines instead.
    # ⚠️ HONEST NOTE: `git ls-remote` with no match prints nothing at
    #    all, so `wc -l` was not wrong in production today. This is
    #    hardening against a wrapper that echoes a blank line, and the
    #    check exists so the hardening cannot be quietly undone.
    rc5, out5 = drive("\n", "0")
    ck("⛔ a BLANK LINE is not a branch",
       rc5 != 0,
       "🔴 `wc -l` reads one empty line as one result. That is a phantom "
       "artifact and it would make the drill pass having proved nothing "
       "— the exact failure this whole file exists for. rc=%d" % rc5)
    rc4, out4 = drive("", "")
    ck("⛔ an unreadable `gh` answer is NOT treated as 'fine'",
       rc4 != 0,
       "🔴 THE MOST DANGEROUS OUTPUT IN THIS REPO IS A FALSE ALL-CLEAR. "
       "If a broken lookup counted as 'a PR exists' the drill would go "
       "green for the second time on the same nothing. rc=%d" % rc4)
    shutil.rmtree(tmp, ignore_errors=True)

note("⛔ WHAT THIS DOES NOT CLAIM: that the agent did the work WELL, or "
     "that the PR is any good. It claims the path executed end to end — "
     "auth, checkout, branch, PR. ➡️ That was the only question the "
     "drill was ever built to answer, and for seven runs it answered it "
     "wrong.")

sys.exit(0)
